# Generated by Django 3.1.4 on 2020-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('link', models.URLField()),
                ('imageID', models.CharField(max_length=1000)),
                ('showBlog', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gitHubLink', models.URLField()),
                ('linkedInLink', models.URLField()),
                ('bloggerLink', models.URLField()),
                ('cvLink', models.URLField()),
                ('imageID', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
                ('codeLink', models.URLField(blank=True)),
                ('demoLink', models.URLField(blank=True)),
                ('imageID', models.CharField(max_length=1000)),
                ('showProject', models.BooleanField(default=True)),
            ],
        ),
    ]
